### ISSUE TITLE
Yeah its not working.

### ISSUE THREAD

**Issue by FoxxSVR2** [distayOFF/LIGRA#1]
![image](https://user-images.githubusercontent.com/84490620/118919279-d54ea280-b8f9-11eb-9c6b-9c7596acf2a3.png)

**Comment by edo44** [comment]
hi,

you have to pass in your discord token in the Config.json file. (or it changed)
![image](https://user-images.githubusercontent.com/39652158/119026050-0932d200-b9a5-11eb-94a4-8ea746fd0683.png)

if you dont know how to get your discord token watch this video: https://www.youtube.com/watch?v=YEgFvgg7ZPI
